### ISSUE TITLE
Ellie Crashes when Angular Augury Chrome extension is active

### ISSUE THREAD

**Issue by mickeyvip** [lukewestby/ellie#10]
Hi and thank you so much for your hard work!

I am not sure this is an actual bug, but I wanted to point out this issue I am having.

Ellie does not work when [Angular's Augury](https://augury.angular.io/) installed and active.

![image](https://user-images.githubusercontent.com/220427/31405945-3e59b3a6-ae08-11e7-9f9d-f67f1fcb0973.png)

**Comment by lukewestby** [comment]
right on! i can work around this no problem.
