### ISSUE TITLE
"Bad recursion" errors don't render properly

### ISSUE THREAD

**Issue by bitterjug** [lukewestby/ellie#14]
[Bad recursion](https://blog.ilias.xyz/help-my-recursive-decoder-caused-a-runtime-exception-453d46a99e1e) error messages have a little line drawing showing the recursive loop. 
These don't look so good in Ellie:
 
![badrecursion](https://user-images.githubusercontent.com/495718/31839759-5e88d27c-b5da-11e7-8b59-68437adb6cb6.png)

[SSCCE](https://ellie-app.com/r8wwRVsqqa1/0)

**Comment by lukewestby** [comment]
@bitterjug that's definitely not what that should look like 😅 i'm gonna track it in #16 since i think it's an issue with the compiler
