### ISSUE TITLE
Many Compiler Errors Are Seen Through "Logs" Section

### ISSUE THREAD

**Issue by mickeyvip** [lukewestby/ellie#19]
The "Logs" section is "transparent":
![image](https://user-images.githubusercontent.com/220427/32132091-a2cad688-bbc5-11e7-89c2-3e7a3b386fb6.png)

Opening "Logs":
![image](https://user-images.githubusercontent.com/220427/32132094-b6d2852c-bbc5-11e7-8c65-4254a13b9c4e.png)

**Comment by lukewestby** [comment]
Fixed by #42
