### ISSUE TITLE
Compiling doesn't do anything on Safari Mobile

### ISSUE THREAD

**Issue by peacememories** [lukewestby/ellie#20]
Hi and thank you for creating and maintaining this wonderful tool.

Unfortunately it seems like while the editing function works like a charm on Safari Mobile, the compile button does nothing, which is a shame because this way I can't view examples users post on slack while on the go (as an example)

I realize this will not be a high priority and is probably caused by lacking api support on the browser side, but it's probably better to have the issue recorded somewhere?

**Comment by lukewestby** [comment]
I think this should be fine after the latest deploy but we'll see. There are some weird, subtle differences in the behavior of actual iOS devices and devices simulated in XCode.

**Comment by lukewestby** [comment]
@peacememories confirmed! this should be all good in iOS 11.2.1 or later

**Comment by peacememories** [comment]
It works now, but it seems Safari on iOS doesn't like web pages pulling 100% cpu? So far my Safari reloaded the page because "a problem occured" after compiling one module. Eventually all modules are compiled but this is not a very fun user experience. Not sure how to solve this though (and if it really is because of the cpu load)
