### ISSUE TITLE
KeyCombo does not work in Firefox

### ISSUE THREAD

**Issue by kormie** [lukewestby/ellie#21]
### Bug Report?

The Control Key code used in `KeyCombo.elm` does not work for Firefox:
  [The control key sub](https://github.com/lukewestby/ellie/blob/b1e57a3f8657ada66d9bb0b1b58bd93b0068f145/client/src/Data/Ellie/KeyCombo.elm#L25) relies on keyCode `91` and `93` which maps correctly in all browsers but Firefox where both map to keycode `224` 

<img width="1665" alt="javascript_event_keycodes_and_javascript_event_keycodes" src="https://user-images.githubusercontent.com/421500/33792989-b9e9b67c-dc63-11e7-81f9-e8d62f2b09c8.png">
<img width="1678" alt="javascript_event_keycodes_and_javascript_event_keycodes" src="https://user-images.githubusercontent.com/421500/33792993-c17692ac-dc63-11e7-9be8-8915a31b5592.png">

I have code locally that should alleviate this error but I'm not sure what the protocol for PRs is on this Repo.

Thanks for the great app, hope I can be of help in the future :)

**Comment by lukewestby** [comment]
@kormie this is on its way into production. thanks for the fix!

**Comment by kormie** [comment]
🚀 🎉 thanks @lukewestby
