### ISSUE TITLE
elm-benchmark shows visual bug only when used within Ellie

### ISSUE THREAD

**Issue by peacememories** [lukewestby/ellie#35]
When using [elm-benchmark](http://package.elm-lang.org/packages/BrianHicks/elm-benchmark/2.0.3) with Ellie, the progress bars extend below their containers. I've seen this on every browser and every system I use, consistently, but only within Ellie.
I assume this is a style clash between [style-elements](http://package.elm-lang.org/packages/mdgriffith/style-elements/4.3.0) and Ellie.

SSCCE: https://ellie-app.com/7KbSZpGgka1/0
![screenshot of the problem](https://user-images.githubusercontent.com/1326334/36343450-d4250f74-140c-11e8-985f-8ca53322a08b.png)

**Comment by lukewestby** [comment]
fixed on https://staging.ellie-app.com/7KbSZpGgka1/0
