### ISSUE TITLE
Promise Polyfill

### ISSUE THREAD

**Issue by ryannhg** [lukewestby/ellie#39]
Hey Luke!

I was trying to share an Ellie with my friend, and he was convinced my CSS styles wouldn't work in IE 11.

So I copied my Ellie URL and pasted it in IE to disprove him. When I hit compile, I got this in the console:

![capture](https://user-images.githubusercontent.com/6187256/38319342-1f91a494-3821-11e8-8080-473889001558.PNG)

It looks like `Promise` isn't defined, and maybe we want to check out a [promise polyfill](https://github.com/stefanpenner/es6-promise)?

This bug can be reproduced by using IE 11 for any app: https://ellie-app.com/new

If you think this is worth the fix, I love using Ellie, and I'd love to make my first contribution by fixing this bug!

Thanks,
Ryan

**Comment by lukewestby** [comment]
@ryannhg thanks for the great issue summary! i'd love a pull request. just to point you in the right direction, the elm apps under `client` already have a promise polyfill but the build manager at https://github.com/lukewestby/ellie/tree/master/make/0.18.0 does not, and the [browser compiler](https://github.com/lukewestby/browser-elm-compiler). i think it's one of those two. feel free to ping me in slack if you have any issues with setup!

**Comment by lukewestby** [comment]
Closing this because #42 is getting pretty close
