### ISSUE TITLE
Searching for packages with short names requires user prefix

### ISSUE THREAD

**Issue by joneshf** [lukewestby/ellie#4]
It looks like there's a minimum length of four characters before the search kicks in. If you search for `svg` or `dom`, for instance, nothing is shown. You can still find the packages by prefixing the user, `elm-lang/svg` or `elm-lang/dom`, respectively.

Not a big deal (since most users have at least two characters so you can prefix a package), but wanted to give a heads up!

**Comment by lukewestby** [comment]
yes! there are also many problems with the search beyond this one. since it isn't a blocker i'm gonna push forward with the long term solution of using a real full text search package on the server so i don't have to do tricks like counting characters in the first place.

**Comment by lukewestby** [comment]
@joneshf should be good to go now

**Comment by joneshf** [comment]
You are an amazing person!

Thanks so much!
