### ISSUE TITLE
Extract JavaScript Elm Compiler as a separate component

### ISSUE THREAD

**Issue by wende** [lukewestby/ellie#5]
Hey there! Tremendous work!
We at [Elchemy](https://github.com/wende/elchemy) would love to have a type-safe demo in the browser. Getting Elm-make as a web worker to work for us would be an amazing feature

However right now from what it seems it's quite hard (without knowing the codebase) to separate the elm-make worker from the rest of the platform and use it elsewhere.

Would really appreciate it to be separated or some help on how could we do it ourselves!
Cheers

**Comment by lukewestby** [comment]
@wende have a look at https://github.com/lukewestby/browser-elm-compiler and see if this would be sufficient for generating the output you need. there's a web worker interface set up in https://github.com/lukewestby/browser-elm-compiler/blob/master/js/worker-interface.js so you just load the script as a web worker via either a proxy or a wrapping script that calls `importScripts` and pass it messages
